---
- name: Configure tomcat-users.xml file
  template:
    src: tomcat-users.xml.j2
    dest: "{{ admin_gui_path }}tomcat-users.xml"
#
- name: Configure /manager/META-INF/context.xml
  template:
    src: manager_context.xml.j2
    dest: "{{ manager_allow_access }}context.xml"
#
- name: Configure /host-manager/META-INF/context.xml
  template:
    src: host-manager_context.xml.j2
    dest: "{{ host_manager_allow_access }}context.xml"
...
