---
- name: To make Tomcat run as a service
  template:
    src: tomcat.service_rhel7.j2
    dest: /etc/systemd/system/tomcat.service
#
- name: Notify systemd that we created a new unit file by typing
  command: systemctl daemon-reload
  args:
    warn: false
...
